### ISSUE TITLE
Special Cases

### ISSUE THREAD

**Issue by RobLoach** [xxorax/node-shell-escape#13]
```
var shellEscape = require('shell-escape')
  var args = ['echo']
  args.push('Hello World!')
  args.push('>')
  args.push('hello.txt')
 var cmd = shellEscape(args)
// => echo 'Hello World!' '>' 'hello.txt'
```

`'>'` should just be `>`

**Comment by marciogranzotto** [comment]
same problem with `&&` been converted to `'&&'`

**Comment by petemoore** [comment]
@RobLoach @marciogranzotto `>` and `&&` are not arguments, but represent shell operations - so this library is correct in escaping them. Note when you run `echo 'Hello World!' > hello.txt` the command run is `echo 'Hello World'` and the shell redirects the standard out from this command to the file `hello.txt`. However, the `echo` command itself has no idea that the shell did that, and if it was to inspect its command line arguments (which is what it does, to decide what to write to standard out), it would only find the tokens `echo` (position 0) - which it would ignore, and `Hello World!` (position 1).

This library provides a mechanism for a given command to be represented in a format that can be executed in a shell. If an echo command truly had positional arguments 0: `echo`, 1: `Hello World!`, 2: `>`, 3: `hello.txt` then it would be correct for this to be written as `echo 'Hello World!' '>' 'hello.txt'` in a shell.

I realise this might not be what you wanted, but I wanted to highlight this library is correctly applying the rules of shell escaping, and the use cases are not quite right for how you are using it. I highlight this mostly in case people stumble on this issue, and think the library is buggy, when in fact it is not, it was just a misuse of the library. Sorry! :-)

**Comment by nicoandra** [comment]
This issue should be closed.

**Comment by RobLoach** [comment]
Thanks for the ping, @nicoandra! Got it working.
