### ISSUE TITLE
Result from shellwords can't be used with child_process.exec

### ISSUE THREAD

**Issue by aslakhellesoy** [xxorax/node-shell-escape#3]
I have been using `child_process.exec` to run commands from `shellescape`:

```javascript
var cmd = "curl 'https://google.com'"; // this comes from shellescape()
require('child_process').exec(cmd, function (err, stdout) {
  if(err) throw err;
  console.log(stdout);
});
```

This broke in 4b9a320d3fc33dbb63a2e14921cf4da1a324aa9b because shellescape now prepends a `$` to each quoted argument. If you run the snippet above with `"curl $'https://google.com'"` you get the following error:

```
Error: Command failed: curl: (1) Protocol $https not supported or disabled in libcurl
```

What was the motivation for prepending the `$`?

**Comment by xxorax** [comment]
This should fix the issue ;)
