### ISSUE TITLE
Escpaing $ in strings

### ISSUE THREAD

**Issue by timkelty** [xxorax/node-shell-escape#8]
``` js
var args = [
    'mysql'
    '-u'
    'xxx'
    '-p'
    'xxx$xx'
    '-h'
    '127.0.0.1'
    '-D'
    'db_production'
];
```

Yields

``` bash
mysql -u'xxx' -p'xxx$xx' -h'127.0.0.1' -D db_production
```

However, for this work, the `$` needs to be escaped:

``` bash
mysql -u'xxx' -p'xxx\$xx' -h'127.0.0.1' -D db_production
```

What's the best way to deal with this?

**Comment by xxorax** [comment]
$ does not need to be escape in single quote string.
Just try:

```
xx=fail
echo 'xx$xx'
```

Output:

```
xx$xx
```

**Comment by timkelty** [comment]
ah, turns out this was because it was nested with double quotes as an arg for an ssh command, which caused the `$` to be misinterpreted.
